version: '3'

services:
  db:
    image: postgres:13.16
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      - PORT=${PORT:-5000}
      - HOST=${HOST:-0.0.0.0}
      - DATABASE_URL=${DATABASE_URL:-postgres://myuser:mypassword@db/mydb}
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  db-data:
