version: '3'

services:
  db:
    image: postgres:13.16
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    environment:
      - PORT=5000
      - HOST=0.0.0.0
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
      - POSTGRES_QUERY_PARAMS=?sslmode=disable
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  db-data:
